[tool.black]
line-length = 80
target-version = ['py38']

[tool.mypy]
exclude = [
    'third_party/',
    'sdk/bin/',
    'venv/',
    '_pb2\.pyi?$',
    '_grpc\.pyi?$',
]

[[tool.mypy.overrides]]
module = "chromite.third_party.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "chromite.api.gen.*"
ignore_errors = true
