name: wolfOS Build and Sync

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Run the workflow on PRs to the main branch

jobs:
  chromiumos-build:
    runs-on: ubuntu-latest
    steps:
      
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python environment (required for repo commands)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install required dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git wget curl
          python3 -m pip install --upgrade pip
          python3 -m pip install repo

      # Initialize repo with the manifest
      - name: Build wolfOS base system
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          TEMP_DIR=$(mktemp -d) && cd $TEMP_DIR && sudo apt-get update && sudo apt-get install -y git curl build-essential python3 python3-pip libssl-dev libncurses5-dev bc bison flex libelf-dev liblzma-dev && curl https://storage.googleapis.com/git-repo-downloads/repo > $TEMP_DIR/repo && chmod a+x $TEMP_DIR/repo && mkdir chromiumos && cd chromiumos && $TEMP_DIR/repo init -u https://chromium.googlesource.com/chromiumos/manifest.git && $TEMP_DIR/repo sync -j$(nproc) && cd ~/chromiumos/src && ./chromiumos/src/scripts/cros_sdk
          repo sync -j16
          cd ChromiumOS/chromite/bin
          ./cros build-packages
          source /opt/chromeos-chroot-tools/setup_chroot.sh
          ./chromite/bin/cbuildozer build chromimos
          source /opt/chromeos-chroot-tools/setup_chroot.sh
          ./chromite/bin/cbuildozer build chromite
          sudo rm -rf $HOME/.repo/
